# Generated by Django 3.2.25 on 2024-03-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.AddField(
            model_name='usuario',
            name='recomendaciones',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimas',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='userid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
